parameters:

    paypal_express_checkout.api_endpoint: https://api-3t.sandbox.paypal.com/nvp
    paypal_express_checkout.controller.route.name: "paypal_express_checkout_execute"
    paypal_express_checkout.routes.loader.class: "PaymentSuite\\PaypalExpressCheckoutBundle\\Router\\PaypalExpressCheckoutRoutesLoader"
