services:
    paypal_express_checkout.routes.loader:
        class: %paypal_express_checkout.routes.loader.class%
        arguments:
            paypal_express_checkout.controller.route.name: %paypal_express_checkout.controller.route.name%
            paypal_express_checkout.controller.route: %paypal_express_checkout.controller.route%
        tags:
            - { name: routing.loader }

    paypal_express_checkout.wrapper:
        class: PaymentSuite\PaypalExpressCheckoutBundle\Services\Wrapper\PaypalExpressCheckoutTransactionWrapper
        arguments:
            name: %paypal_express_checkout.username%
            password: %paypal_express_checkout.password%
            signature: %paypal_express_checkout.signature%
            endpoint: %paypal_express_checkout.api_endpoint%
            debug: %paypal_express_checkout.debug%

    paypal_checkout.manager:
        class: PaymentSuite\PaypalExpressCheckoutBundle\Services\PaypalExpressCheckoutManager
        arguments:
            payment.event.dispatcher: @payment.event.dispatcher
            payment.transaction.wrapper: @paypal_express_checkout.wrapper
            payment.bridge: @payment.bridge
