services:
    paypal_express_checkout.routes.loader:
        class: PaymentSuite\PaypalExpressCheckoutBundle\Router\PaypalExpressCheckoutRoutesLoader
        tags:
            - { name: routing.loader }
    paypal_express_checkout.wrapper:
        class: PaymentSuite\PaypalExpressCheckoutBundle\Services\Wrapper\PaypalExpressCheckoutTransactionWrapper
        arguments:
            - %paypal_checkout.username%
            - %paypal_checkout.password%
            - %paypal_checkout.signature%
            - %paypal_checkout.api_endpoint%
            - %paypal_checkout.debug%
