services:
    paypal_express_checkout.routes.loader:
        class: PaymentSuite\PaypalExpressCheckoutBundle\Router\PaypalExpressCheckoutRoutesLoader
        tags:
            - { name: routing.loader }